version: '3'
services:
  db:
    container_name: test_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB:  test
    ports:
      - "5432:5432"